services:
  postgres:
    image: postgres:16-alpine
    container_name: schemasentry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schemasentry_test
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schemasentry_test"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
